export const WORLD_SIZE = 1024000; //TILE_SIZE * 2000
export const EARTH_RADIUS = 6371008.8;
export const PROJECTION_WORLD_SIZE = WORLD_SIZE / (EARTH_RADIUS * Math.PI * 2);
export const MERCATOR_A = EARTH_RADIUS;
export const DEG2RAD = Math.PI / 180;
export const RAD2DEG = 180 / Math.PI;
export const EARTH_CIRCUMFERENCE = 2 * Math.PI * EARTH_RADIUS; //40075000, // In meters
export const EARTH_CIRCUMFERENCE_EQUATOR = 40075017;
export const FOV_ORTHO = 0.1 / 180 * Math.PI; // closest to 0
export const FOV = Math.atan(3 / 4); // Math.atan(3/4) radians. If this value is changed, FOV_DEGREES must be calculated
export const FOV_DEGREES = FOV * 180 / Math.PI; // Math.atan(3/4) in degrees
export const TILE_SIZE = 512;